### ISSUE TITLE
Custom cursor component

### ISSUE THREAD

**Issue by SKOLZ** [ajmnz/custom-cursor-react#19]
Thanks for maintaining this library, I think it would be a great addition to the lib to let the developer change the HTML that is rendered. In order to implement this, I think a wrapper element could have a class added/removed to show that a target is hovered.

**Comment by ajmnz** [comment]
I've been procrastinating a TypeScript rewrite and a hooks API for some time now.
Will take your request into consideration when I actually get to work on the library 👍🏼
