### ISSUE TITLE
Can't resolve `gsap`

### ISSUE THREAD

**Issue by mukhrr** [ajmnz/custom-cursor-react#20]
Hi! I unexpectedly faced such kind of error. Let me know if the error is from my computer though.

![image](https://user-images.githubusercontent.com/71601329/170188134-d645731f-abc3-45ef-9e55-45534189ba6b.png)

**Comment by ajmnz** [comment]
Hey, gsap is listed as a peer dependency, so you have to install it yourself

https://github.com/ajmnz/custom-cursor-react/blob/6dc317043f7a948f61b8f87d2dd81f2c699c88f2/package.json#L37-L41

**Comment by ayoubkhan558** [comment]
> Hey, gsap is listed as a peer dependency, so you have to install it yourself
> 
> https://github.com/ajmnz/custom-cursor-react/blob/6dc317043f7a948f61b8f87d2dd81f2c699c88f2/package.json#L37-L41

You have to install a whole new library, just for the cursor. Does not make sense.
