### ISSUE TITLE
Is there a way to change the color/other attributes of the cursor on target?

### ISSUE THREAD

**Issue by AmeyVijeesh** [ajmnz/custom-cursor-react#22]
On target, I want the cursor to change color, and change maybe some of its attributes. It is possible?

P.S it would be great if there was a feature to add text on the cursor :)

**Comment by ajmnz** [comment]
It is not possible to change color on target hover, since there's no onChange callback available. Though you could dynamically change the `fill` prop when a target is hovered using React Context or other state libraries.

PRs are welcome too!
